### ISSUE TITLE
Issue during "ng build"

### ISSUE THREAD

**Issue by ashishcomps** [Hygieia/UI#105]
ERROR in src/app/admin_modules/admin_dashboard/admin-dashboard-modules.ts(32,45): error TS2307: Cannot find module './dashboard/admin-dashboard/modal/edit-dashboard-modal /edit-dashboard-modal.component'.
src/app/admin_modules/admin_dashboard/dashboard/admin-dashboard/edit-dashboard/edit-dashboard.component.ts(7,45): error TS2307: Cannot find module '../modal/edit-dashboard-modal /edit-dashboard-modal.component'.

**Comment by rvema** [comment]
There might be an issue with your environment setup as we have put continuous CI checks for compilation on every PR.
