### ISSUE TITLE
Issue in Git Clone : Only Windows

### ISSUE THREAD

**Issue by prash897** [Hygieia/UI#111]
Hi
The git clone is failing because of a space in path , Mac is working fine, It shows issue in Git Clone in Windows Only

![image](https://user-images.githubusercontent.com/11367273/86270541-04c4c580-bbe9-11ea-98d7-d9929887b72a.png)

**Comment by Courtneyp123** [comment]
@prash897 I'll edit that for you!

**Comment by Courtneyp123** [comment]
@prash897 Let me know if it works for you!

**Comment by prash897** [comment]
@Courtneyp123 , Thanks Resolved
