### ISSUE TITLE
Display overlapped

### ISSUE THREAD

**Issue by VivekBuzruk** [Hygieia/UI#161]
Looks like this UI is still work in progress. 

![newUI](https://user-images.githubusercontent.com/24850734/94090344-f6c2c180-fe32-11ea-926f-24190e5b6194.png)
![oldU](https://user-images.githubusercontent.com/24850734/94090441-3db0b700-fe33-11ea-9057-a4a8c6b3002a.png)

**Comment by Courtneyp123** [comment]
Hi @VivekBuzruk thanks for your note. Yes, the UI is still in progress, but we'll get this overlap sorted out soon!

**Comment by Courtneyp123** [comment]
Noted and fixed in PR.
