### ISSUE TITLE
I would like to contribute 

### ISSUE THREAD

**Issue by sundeepk1** [Hygieia/UI#23]
Hi Team, 

I would like to contribute towards dockerization of the components of Hygieia and would like to deploy the same in Kubernetes Cluster. 

Can you guide me with ref to this . 

Regards,
Sundeep Kumar P

**Comment by Sbrenthughes** [comment]
@sundeepk1 This repo is a WIP and isn't being monitored for Issues. Could you please open an issue for contribution process on `Hygieia/Hygieia`?
